# Generated by Django 2.2 on 2019-04-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=1024)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_package_list',
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 't_package_type',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('purview', models.IntegerField()),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_person',
            },
        ),
        migrations.CreateModel(
            name='ProgrameGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=1024)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_programe_group',
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=16)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('desc', models.CharField(max_length=1024)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Package')),
            ],
            options={
                'db_table': 't_package_version',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='package_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Person'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.PackageType'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=64)),
                ('device_ip', models.CharField(max_length=16)),
                ('status', models.IntegerField(choices=[(0, 'offline'), (1, 'online'), (-1, 'error')])),
                ('desc', models.CharField(max_length=1024)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.ProgrameGroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Person')),
            ],
            options={
                'db_table': 't_device_list',
            },
        ),
    ]
